name: Test Python

on:
  push:
    paths:
      - .github/workflows/test-python.yml
      - python/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          cd python
          pip install -r requirements.txt

      - name: Test
        run: |
          cd python
          python -m pytest

