name: Test JavaScript

on:
  push:
    paths:
      - .github/workflows/test-javascript.yml
      - javascript/**

defaults:
  run:
    working-directory: javascript

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            javascript/node_modules
          key: ${{ runner.os }}-${{ hashFiles('javascript/package.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test
