name: Test JavaScript

on:
  push:
    paths:
      - .github/workflows/test-javascript.yml
      - javascript/**

defaults:
  run:
    working-directory: javascript

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test
